apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  ports:
  - name: "3005"
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
