apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms
  name: orders-ms
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: orders-ms
  type: ClusterIP
status:
  loadBalancer: {}
